### ISSUE TITLE
Data Synchronization Across Devices

### ISSUE THREAD

**Issue by wonderer007** [Ditectrev/Amazon-Web-Services-AWS-Developer-Associate-DVA-C02-Practice-Tests-Exams-Questions-Answers#1]
How the answer for the below question is **Amazon Cognitio**

https://github.com/Ditectrev/Amazon-Web-Services-AWS-Developer-Associate-DVA-C02-Practice-Tests-Exams-Questions-Answers#a-gaming-company-is-developing-a-mobile-game-application-for-ios-and-android-platforms-this-mobile-game-securely-stores-user-data-locally-on-the-device-the-company-wants-to-allow-users-to-use-multiple-device-for-the-game-which-requires-user-data-synchronization-across-devicewhich-service-should-be-used-to-synchronize-user-data-across-devices-without-the-need-to-create-a-backend-application

**Comment by du-nong-0070** [comment]
The requirement is mainly to store the user data and credentials without BE that can be used to sign in on multiple devices (current is stored locally).
Hence, the correct answer is **Amazon Cognitio**.

**Comment by danieldanielecki** [comment]
@du-nong-0070 is correct, https://aws.amazon.com/cognito/faqs/ might help to clarify as well.
