### ISSUE TITLE
Question 13

### ISSUE THREAD

**Issue by ignacio-magno** [Ditectrev/Amazon-Web-Services-AWS-Developer-Associate-DVA-C02-Practice-Tests-Exams-Questions-Answers#12]
the answer corret not must be 2 and 4?.
sam publicsh not exists, and sam deploy not work if previous call sam build.
Then must be sam deploy and sam publish, 
The command init was invoked when in question says "he developer has used the AWS SAM CLI to create the project."

**Comment by danieldanielecki** [comment]
Fixed in https://github.com/Ditectrev/Amazon-Web-Services-AWS-Developer-Associate-DVA-C02-Practice-Tests-Exams-Questions-Answers/commit/21c44c5da5133b67ff316203b7acbb4c5477cd82, thanks a lot and more feedback is welcome! ❤️
