### ISSUE TITLE
wrong answers

### ISSUE THREAD

**Issue by vsosevic** [Ditectrev/Amazon-Web-Services-AWS-Developer-Associate-DVA-C02-Practice-Tests-Exams-Questions-Answers#26]
126 - 1st is correct
132 - 2nd is correct
136 - 3rd is correct
139 - 4th is correct
143 - 3rd is correct
145 - 1st is correct
158 - 2nd is correct
159 - 3rd is correct
162 - 2nd is correct
162 - 2nd is correct
175 - 1st is correct
176 - 1st is correct
181 - 3rd and 5th are correct
184 - 2nd is correct
187 - no correct presented. Correct is - "Edit the bucket policy of the assets bucket to allow access from the code bucket."
195 - 1, 3
204 - 4th and 5th are correct
206 - 4th is correct
210 - 1st is correct
215 - 4th is correct
221 - 3rd is correct
237 - 1st is corrert
241 - 2nd and 3rd are correct
266 - 4th is correct
274 - 4th is correct
276 - 1st is correct
278 - 2nd is correct
284 - 4th is correct
285 - 2nd and 3rd are correct
293 - 3rd is correct
294 - 3rd is correct
298 - 4th is correct
300 - 3rd is correct
301 - 4th is correct
308 - 1st is correct
309 - 4
314 - 2nd is correct
315 - 4th is correct
317 - 4
320 - 2
323 - 2
328 - 3
329 - 1, 2
330 - 2
331 - 2, 5
332 - 1
333 - 3
338 - 4
339 - 2, 5
357 - 2
358 - 2, 4
368 - 4
369 - 1,2
370 - 4
379 - 2
381 - 3

**Comment by vsosevic** [comment]
> 126 - 1st is correct 132 - 2nd is correct 136 - 3rd is correct 139 - 4th is correct 143 - 3rd is correct 145 - 1st is correct 158 - 2nd is correct 159 - 3rd is correct 162 - 2nd is correct

**Comment by danieldanielecki** [comment]
@vsosevic why did you close it? Are you planning to submit a PR?

**Comment by vsosevic** [comment]
> @vsosevic why did you close it? Are you planning to submit a PR?

oh, that was by accident. sorry.

**Comment by vsosevic** [comment]
I'm still in the process of reviewing those question so will be updating this issue today and tomorrow. Does it work for you?

**Comment by danieldanielecki** [comment]
> I'm still in the process of reviewing those question so will be updating this issue today and tomorrow. Does it work for you?

of course, take your time ;-)

**Comment by vsosevic** [comment]
@danieldanielecki  Quite a few mistakes out there. Where those answer were coming from?

**Comment by danieldanielecki** [comment]
> @danieldanielecki Quite a few mistakes out there. Where were those answers coming from?

mix of multiple sources, like 3 or 4. That time our process wasn't as good :-(

**Comment by danieldanielecki** [comment]
@vsosevic would you mind to create a PR?

**Comment by vsosevic** [comment]
I'm done. Not sure if I still have a capacity to apply all those changes to the code. Sorry

**Comment by danieldanielecki** [comment]
> 126 - 1st is correct 132 - 2nd is correct 136 - 3rd is correct 139 - 4th is correct 143 - 3rd is correct 145 - 1st is correct 158 - 2nd is correct 159 - 3rd is correct 162 - 2nd is correct 162 - 2nd is correct 175 - 1st is correct 176 - 1st is correct 181 - 3rd and 5th are correct 184 - 2nd is correct 187 - no correct presented. Correct is - "Edit the bucket policy of the assets bucket to allow access from the code bucket." 195 - 1, 3 204 - 4th and 5th are correct 206 - 4th is correct 210 - 1st is correct 215 - 4th is correct 221 - 3rd is correct 237 - 1st is corrert 241 - 2nd and 3rd are correct 266 - 4th is correct 274 - 4th is correct 276 - 1st is correct 278 - 2nd is correct 284 - 4th is correct 285 - 2nd and 3rd are correct 293 - 3rd is correct 294 - 3rd is correct 298 - 4th is correct 300 - 3rd is correct 301 - 4th is correct 308 - 1st is correct 309 - 4 314 - 2nd is correct 315 - 4th is correct 317 - 4 320 - 2 323 - 2 328 - 3 329 - 1, 2 330 - 2 331 - 2, 5 332 - 1 333 - 3 338 - 4 339 - 2, 5 357 - 2 358 - 2, 4 368 - 4 369 - 1,2 370 - 4 379 - 2 381 - 3

- 126: disagree, fixed question tho, with 3rd,
- 132: agree & fixed,
- 136: agree & fixed,
- 139: agree & fixed,
- 143: agree & fixed,
- 145: agree & fixed,
- 158: agree & fixed,
- 159: 3rd was already there,
- 162: agree & fixed,
- 175: agree & fixed,
- 176: disagree, fixed question tho, with 4th,
- 181: agree & fixed,
- 284: agree & fixed,

Commit with these changes https://github.com/Ditectrev/Amazon-Web-Services-AWS-Developer-Associate-DVA-C02-Practice-Tests-Exams-Questions-Answers/commit/b4f1c740842efe4913a2fd8367628f96222d704a

**Comment by danieldanielecki** [comment]
> 126 - 1st is correct 132 - 2nd is correct 136 - 3rd is correct 139 - 4th is correct 143 - 3rd is correct 145 - 1st is correct 158 - 2nd is correct 159 - 3rd is correct 162 - 2nd is correct 162 - 2nd is correct 175 - 1st is correct 176 - 1st is correct 181 - 3rd and 5th are correct 184 - 2nd is correct 187 - no correct presented. Correct is - "Edit the bucket policy of the assets bucket to allow access from the code bucket." 195 - 1, 3 204 - 4th and 5th are correct 206 - 4th is correct 210 - 1st is correct 215 - 4th is correct 221 - 3rd is correct 237 - 1st is corrert 241 - 2nd and 3rd are correct 266 - 4th is correct 274 - 4th is correct 276 - 1st is correct 278 - 2nd is correct 284 - 4th is correct 285 - 2nd and 3rd are correct 293 - 3rd is correct 294 - 3rd is correct 298 - 4th is correct 300 - 3rd is correct 301 - 4th is correct 308 - 1st is correct 309 - 4 314 - 2nd is correct 315 - 4th is correct 317 - 4 320 - 2 323 - 2 328 - 3 329 - 1, 2 330 - 2 331 - 2, 5 332 - 1 333 - 3 338 - 4 339 - 2, 5 357 - 2 358 - 2, 4 368 - 4 369 - 1,2 370 - 4 379 - 2 381 - 3

- 184: in fact 2nd & 3rd are both correct, but 2nd is better one - fixed,
- 187: agree & fixed,
- 195: agree & fixed,
- 204: agree & fixed,
- 206: agree & fixed,
- 210: agree & fixed,
- 215: agree & fixed.

Commit with these changes https://github.com/Ditectrev/Amazon-Web-Services-AWS-Developer-Associate-DVA-C02-Practice-Tests-Exams-Questions-Answers/commit/b20fbd394990d9fe7d4ce8e06c309ea15c90a7a5.

**Comment by danieldanielecki** [comment]
> 126 - 1st is correct 132 - 2nd is correct 136 - 3rd is correct 139 - 4th is correct 143 - 3rd is correct 145 - 1st is correct 158 - 2nd is correct 159 - 3rd is correct 162 - 2nd is correct 162 - 2nd is correct 175 - 1st is correct 176 - 1st is correct 181 - 3rd and 5th are correct 184 - 2nd is correct 187 - no correct presented. Correct is - "Edit the bucket policy of the assets bucket to allow access from the code bucket." 195 - 1, 3 204 - 4th and 5th are correct 206 - 4th is correct 210 - 1st is correct 215 - 4th is correct 221 - 3rd is correct 237 - 1st is corrert 241 - 2nd and 3rd are correct 266 - 4th is correct 274 - 4th is correct 276 - 1st is correct 278 - 2nd is correct 284 - 4th is correct 285 - 2nd and 3rd are correct 293 - 3rd is correct 294 - 3rd is correct 298 - 4th is correct 300 - 3rd is correct 301 - 4th is correct 308 - 1st is correct 309 - 4 314 - 2nd is correct 315 - 4th is correct 317 - 4 320 - 2 323 - 2 328 - 3 329 - 1, 2 330 - 2 331 - 2, 5 332 - 1 333 - 3 338 - 4 339 - 2, 5 357 - 2 358 - 2, 4 368 - 4 369 - 1,2 370 - 4 379 - 2 381 - 3

- 221: agree & fixed,
- 237: agree & fixed,
- 241: agree & fixed,
- 266: agree & fixed.

Commit with these changes: https://github.com/Ditectrev/Amazon-Web-Services-AWS-Developer-Associate-DVA-C02-Practice-Tests-Exams-Questions-Answers/commit/286d7831e3690078a3b54e1f8e92b4bcd275681b.

**Comment by danieldanielecki** [comment]
> 126 - 1st is correct 132 - 2nd is correct 136 - 3rd is correct 139 - 4th is correct 143 - 3rd is correct 145 - 1st is correct 158 - 2nd is correct 159 - 3rd is correct 162 - 2nd is correct 162 - 2nd is correct 175 - 1st is correct 176 - 1st is correct 181 - 3rd and 5th are correct 184 - 2nd is correct 187 - no correct presented. Correct is - "Edit the bucket policy of the assets bucket to allow access from the code bucket." 195 - 1, 3 204 - 4th and 5th are correct 206 - 4th is correct 210 - 1st is correct 215 - 4th is correct 221 - 3rd is correct 237 - 1st is corrert 241 - 2nd and 3rd are correct 266 - 4th is correct 274 - 4th is correct 276 - 1st is correct 278 - 2nd is correct 284 - 4th is correct 285 - 2nd and 3rd are correct 293 - 3rd is correct 294 - 3rd is correct 298 - 4th is correct 300 - 3rd is correct 301 - 4th is correct 308 - 1st is correct 309 - 4 314 - 2nd is correct 315 - 4th is correct 317 - 4 320 - 2 323 - 2 328 - 3 329 - 1, 2 330 - 2 331 - 2, 5 332 - 1 333 - 3 338 - 4 339 - 2, 5 357 - 2 358 - 2, 4 368 - 4 369 - 1,2 370 - 4 379 - 2 381 - 3

- 293: agree & fixed,
- 294: agree & fixed,
- 298: agree & fixed,
- 300: agree & fixed, 
- 301: agree & fixed.

Commit with these changes: https://github.com/Ditectrev/Amazon-Web-Services-AWS-Developer-Associate-DVA-C02-Practice-Tests-Exams-Questions-Answers/commit/f2133cbeae726c779da731aad5e4ee3f0c7d7a9e.

**Comment by danieldanielecki** [comment]
> 126 - 1st is correct 132 - 2nd is correct 136 - 3rd is correct 139 - 4th is correct 143 - 3rd is correct 145 - 1st is correct 158 - 2nd is correct 159 - 3rd is correct 162 - 2nd is correct 162 - 2nd is correct 175 - 1st is correct 176 - 1st is correct 181 - 3rd and 5th are correct 184 - 2nd is correct 187 - no correct presented. Correct is - "Edit the bucket policy of the assets bucket to allow access from the code bucket." 195 - 1, 3 204 - 4th and 5th are correct 206 - 4th is correct 210 - 1st is correct 215 - 4th is correct 221 - 3rd is correct 237 - 1st is corrert 241 - 2nd and 3rd are correct 266 - 4th is correct 274 - 4th is correct 276 - 1st is correct 278 - 2nd is correct 284 - 4th is correct 285 - 2nd and 3rd are correct 293 - 3rd is correct 294 - 3rd is correct 298 - 4th is correct 300 - 3rd is correct 301 - 4th is correct 308 - 1st is correct 309 - 4 314 - 2nd is correct 315 - 4th is correct 317 - 4 320 - 2 323 - 2 328 - 3 329 - 1, 2 330 - 2 331 - 2, 5 332 - 1 333 - 3 338 - 4 339 - 2, 5 357 - 2 358 - 2, 4 368 - 4 369 - 1,2 370 - 4 379 - 2 381 - 3

- 308: agree & fixed,
- 309: agree & fixed,
- 314: agree & fixed,
- 315: agree & fixed,
- 317: agree & fixed.

Commit with these changes: https://github.com/Ditectrev/Amazon-Web-Services-AWS-Developer-Associate-DVA-C02-Practice-Tests-Exams-Questions-Answers/commit/303c5e7786d6b65d2926871d9163cc55370124fb.

**Comment by danieldanielecki** [comment]
> 126 - 1st is correct 132 - 2nd is correct 136 - 3rd is correct 139 - 4th is correct 143 - 3rd is correct 145 - 1st is correct 158 - 2nd is correct 159 - 3rd is correct 162 - 2nd is correct 162 - 2nd is correct 175 - 1st is correct 176 - 1st is correct 181 - 3rd and 5th are correct 184 - 2nd is correct 187 - no correct presented. Correct is - "Edit the bucket policy of the assets bucket to allow access from the code bucket." 195 - 1, 3 204 - 4th and 5th are correct 206 - 4th is correct 210 - 1st is correct 215 - 4th is correct 221 - 3rd is correct 237 - 1st is corrert 241 - 2nd and 3rd are correct 266 - 4th is correct 274 - 4th is correct 276 - 1st is correct 278 - 2nd is correct 284 - 4th is correct 285 - 2nd and 3rd are correct 293 - 3rd is correct 294 - 3rd is correct 298 - 4th is correct 300 - 3rd is correct 301 - 4th is correct 308 - 1st is correct 309 - 4 314 - 2nd is correct 315 - 4th is correct 317 - 4 320 - 2 323 - 2 328 - 3 329 - 1, 2 330 - 2 331 - 2, 5 332 - 1 333 - 3 338 - 4 339 - 2, 5 357 - 2 358 - 2, 4 368 - 4 369 - 1,2 370 - 4 379 - 2 381 - 3

- 323: agree & fixed,
- 328: agree & fixed,
- 329: partially agree (1 & 3) & fixed,
- 330: agree & fixed,
- 331: agree & fixed,
- 332: agree & fixed,
- 333: agree & fixed.

Commit with these changes: https://github.com/Ditectrev/Amazon-Web-Services-AWS-Developer-Associate-DVA-C02-Practice-Tests-Exams-Questions-Answers/commit/5669bff2a428e06ab8aaa53bbb1a6e5f47bef9fe.

**Comment by danieldanielecki** [comment]
Update: agreed with 329 for 1 & 2, commit https://github.com/Ditectrev/Amazon-Web-Services-AWS-Developer-Associate-DVA-C02-Practice-Tests-Exams-Questions-Answers/commit/93cd250a7bc258bd57fe9881165eba24df775682.

**Comment by danieldanielecki** [comment]
> 126 - 1st is correct 132 - 2nd is correct 136 - 3rd is correct 139 - 4th is correct 143 - 3rd is correct 145 - 1st is correct 158 - 2nd is correct 159 - 3rd is correct 162 - 2nd is correct 162 - 2nd is correct 175 - 1st is correct 176 - 1st is correct 181 - 3rd and 5th are correct 184 - 2nd is correct 187 - no correct presented. Correct is - "Edit the bucket policy of the assets bucket to allow access from the code bucket." 195 - 1, 3 204 - 4th and 5th are correct 206 - 4th is correct 210 - 1st is correct 215 - 4th is correct 221 - 3rd is correct 237 - 1st is corrert 241 - 2nd and 3rd are correct 266 - 4th is correct 274 - 4th is correct 276 - 1st is correct 278 - 2nd is correct 284 - 4th is correct 285 - 2nd and 3rd are correct 293 - 3rd is correct 294 - 3rd is correct 298 - 4th is correct 300 - 3rd is correct 301 - 4th is correct 308 - 1st is correct 309 - 4 314 - 2nd is correct 315 - 4th is correct 317 - 4 320 - 2 323 - 2 328 - 3 329 - 1, 2 330 - 2 331 - 2, 5 332 - 1 333 - 3 338 - 4 339 - 2, 5 357 - 2 358 - 2, 4 368 - 4 369 - 1,2 370 - 4 379 - 2 381 - 3

- 338: agree & fixed,
- 339: partially agree (1 & 2) & fixed.

Commit with these changes: https://github.com/Ditectrev/Amazon-Web-Services-AWS-Developer-Associate-DVA-C02-Practice-Tests-Exams-Questions-Answers/commit/fc17fb4931d816aaae5dd9912396386346f5bc95.

**Comment by danieldanielecki** [comment]
> 126 - 1st is correct 132 - 2nd is correct 136 - 3rd is correct 139 - 4th is correct 143 - 3rd is correct 145 - 1st is correct 158 - 2nd is correct 159 - 3rd is correct 162 - 2nd is correct 162 - 2nd is correct 175 - 1st is correct 176 - 1st is correct 181 - 3rd and 5th are correct 184 - 2nd is correct 187 - no correct presented. Correct is - "Edit the bucket policy of the assets bucket to allow access from the code bucket." 195 - 1, 3 204 - 4th and 5th are correct 206 - 4th is correct 210 - 1st is correct 215 - 4th is correct 221 - 3rd is correct 237 - 1st is corrert 241 - 2nd and 3rd are correct 266 - 4th is correct 274 - 4th is correct 276 - 1st is correct 278 - 2nd is correct 284 - 4th is correct 285 - 2nd and 3rd are correct 293 - 3rd is correct 294 - 3rd is correct 298 - 4th is correct 300 - 3rd is correct 301 - 4th is correct 308 - 1st is correct 309 - 4 314 - 2nd is correct 315 - 4th is correct 317 - 4 320 - 2 323 - 2 328 - 3 329 - 1, 2 330 - 2 331 - 2, 5 332 - 1 333 - 3 338 - 4 339 - 2, 5 357 - 2 358 - 2, 4 368 - 4 369 - 1,2 370 - 4 379 - 2 381 - 3

- 357: agree & fixed,
- 358: agree & fixed.

Commit with these changes: https://github.com/Ditectrev/Amazon-Web-Services-AWS-Developer-Associate-DVA-C02-Practice-Tests-Exams-Questions-Answers/commit/ca5b33edf93688caef464d299b02dd25df8aa3ab.

**Comment by danieldanielecki** [comment]
> 126 - 1st is correct 132 - 2nd is correct 136 - 3rd is correct 139 - 4th is correct 143 - 3rd is correct 145 - 1st is correct 158 - 2nd is correct 159 - 3rd is correct 162 - 2nd is correct 162 - 2nd is correct 175 - 1st is correct 176 - 1st is correct 181 - 3rd and 5th are correct 184 - 2nd is correct 187 - no correct presented. Correct is - "Edit the bucket policy of the assets bucket to allow access from the code bucket." 195 - 1, 3 204 - 4th and 5th are correct 206 - 4th is correct 210 - 1st is correct 215 - 4th is correct 221 - 3rd is correct 237 - 1st is corrert 241 - 2nd and 3rd are correct 266 - 4th is correct 274 - 4th is correct 276 - 1st is correct 278 - 2nd is correct 284 - 4th is correct 285 - 2nd and 3rd are correct 293 - 3rd is correct 294 - 3rd is correct 298 - 4th is correct 300 - 3rd is correct 301 - 4th is correct 308 - 1st is correct 309 - 4 314 - 2nd is correct 315 - 4th is correct 317 - 4 320 - 2 323 - 2 328 - 3 329 - 1, 2 330 - 2 331 - 2, 5 332 - 1 333 - 3 338 - 4 339 - 2, 5 357 - 2 358 - 2, 4 368 - 4 369 - 1,2 370 - 4 379 - 2 381 - 3

- 368: agree & fixed,
- 369: agree & fixed,
- 370: agree & fixed,
- 379: agree & fixed,
- 381: agree & fixed.

Commit with these changes: https://github.com/Ditectrev/Amazon-Web-Services-AWS-Developer-Associate-DVA-C02-Practice-Tests-Exams-Questions-Answers/commit/614f8a6eef18beb0939264b03f8ae2b6e56d07c7.

@vsosevic, thanks for the priceless contribution and for making the course better :) 
Feel free to find me on Discord for some goodies whenever you're preparing for your next certificate from those ones we have in offer :)
