### ISSUE TITLE
Incorrect answers  to question 120 and question 133

### ISSUE THREAD

**Issue by Olat-nji** [Ditectrev/Amazon-Web-Services-AWS-Developer-Associate-DVA-C02-Practice-Tests-Exams-Questions-Answers#30]
### A company has developed a new serverless application using AWS Lambda functions that will be deployed using the AWS Serverless Application Model (AWS SAM) CLI. Which step should the developer complete prior to deploying the application?

- [x] Compress the application to a .zip file and upload it into AWS Lambda.
- [ ] Test the new AWS Lambda function by first tracing it in AWS X-Ray.
- [ ] Bundle the serverless application using a SAM package.
- [ ] Create the application environment using the eb create my-env command.

C is the right answer

### A developer is creating a script to automate the deployment process for a serverless application. The developer wants to use an existing AWS Serverless Application Model (AWS SAM) template for the application. What should the developer use for the project? (Choose TWO)

- [ ] Call aws cloudformation package to create the deployment package. Call aws cloudformation deploy to deploy the package afterward.
- [ ] Call sam package to create the deployment package. Call sam deploy to deploy the package afterward.
- [x] Call aws s3 cp to upload the AWS SAM template to Amazon S3. Call aws lambda update-function-code to create the application.
- [ ] Create a ZIP package locally and call aws serverlessrepo create-application to create the application.
- [x] Create a ZIP package and upload it to Amazon S3. Call aws cloudformation create-stack to create the application.

A and B are the right answers

I already made a PR, I hope that's alright

**Comment by danieldanielecki** [comment]
closed in #29
